### ISSUE TITLE
Support for connection pools

### ISSUE THREAD

**Issue by theasp** [r0man/sqlingvo.node#5]
Any thoughts on adding support for the connection pool built into the pg driver?  I cooked up the following to emulate a bit of `postgres.async`, maybe it would be useful.  

https://gist.github.com/theasp/8b1c35134788ba88edca12f52ad75f27

**Comment by r0man** [comment]
@theasp No, not yet. But patch welcome! ;)

**Comment by r0man** [comment]
@theasp The async driver now uses a connection pool. Try out `0.2.1`.
