### ISSUE TITLE
Incorrect usage of connection pools

### ISSUE THREAD

**Issue by nenadalm** [r0man/sqlingvo.node#8]
Hi. As I was browsing the code - it looks like pools are created for each query and then removed again (or maybe I misunderstood something)?

Documentation says that I should call `connect` before running query - which is creating new pool and returns clientl: https://github.com/r0man/sqlingvo.node/blob/master/src/sqlingvo/node/async.cljs#L42

and then I should call `disconnect` when I am done with the query which is removing the client: https://github.com/r0man/sqlingvo.node/blob/master/src/sqlingvo/node/async.cljs#L52.

I think it should work the way that new pool is instantiated: https://node-postgres.com/api/pool

and when somebody wants to execute query - `query` method should be called on the pool. When somebody wants to do more queries enclosed within transaction perhaps - `connect` should be called which returns client (which is also way it seems to work now) and when work is finished - `release` should be called so that the connection can be reused (instead of closing it - which seems to be the way it is now).

**Comment by r0man** [comment]
@nenadalm Yes, you are right. I pushed a fix to master. Can you try `0.2.2-SNAPSHOT`?

You can see in the tests how to use it:
https://github.com/r0man/sqlingvo.node/blob/master/test/sqlingvo/node/async_test.cljs#L118

**Comment by nenadalm** [comment]
I didn't test it yet - I was just looking at the code.

If I understand correctly - you can create new pool only in go block (as it returns channel): https://github.com/r0man/sqlingvo.node/blob/759dd57030a3cd678a9e5004b84f8f0b9d39e9aa/src/sqlingvo/node/async.cljs#L103 so you cannot create some global variable and use it then for multiple queries?

So I can't do something like:
```clojure
;; this is how currently `db` is created (without instantiated pool)
(def db-config (node/db connection-string))

;; this is how it would be nice to create single pool for entire application which can then be used by all queries (so it's probably same map as `db-config` except it contains `:pool` in addition)
(def db-with-connection-pool (node/start db-config))

;; fn using client acquired from the pool
(defn get-usernames [f]
  (go (let [db (<? (node/connect db-with-connection-pool) ;; acquiring client from the pool
                   )]
        (f (<!? (sql/select db :user [:username])))
        (node/release db) ;; releasing client so somebody else can acquire it from the pool
        )))

;; fn executing queries without acquiring client
(defn get-usernames-without-acquiring-client [f]
  (go (f (<!? (node/execute (sql/select db-with-connection-pool :user [:username])) ;; executing query on pool (which will use an available client)
              ))))

```

I might send pr some day (it might take a few though...).

**Comment by nenadalm** [comment]
also note that the db created using `(node/db connection-string)` could be atom which could then be altered by `(node/start db-config)` to contain the `:pool` (so if somebody doesn't want to have it permanently in their app - they can just remove it using `db/stop`...

**Comment by r0man** [comment]
@nenadalm Ok, I think this is what you had in mind:

https://github.com/r0man/sqlingvo.node/commit/6d1c7d536d4a858e0e653ce9fb05d9f17d01f31d

Otherwise, feel free to submit a PR how you think the API would be best.

**Comment by nenadalm** [comment]
wow - thanks - that seems to be what I had in mind :) I only looked at the code so far, but I'll try it in a week. You're very fast :)

I'll close this for now and reopen if I will have any issues.

**Comment by r0man** [comment]
perfect. you are welcome
